# Generated by Django 5.0.3 on 2024-04-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('directions', models.TextField(verbose_name='Directions')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
