# Generated by Django 5.0.3 on 2024-04-02 12:46

from django.db import migrations

def create_data(apps, schema_editor):
    Recipes = apps.get_model('Recipes', 'Recipes')
    Recipes(title="Toast", ingredients='Bread,Butter', directions="Toast bread til satisfied. Then spread butter.").save()
    Recipes(title="PB&J", ingredients='Bread, Peanut Butter, Jelly', directions="Toast bread til satisfied. Then spread peanut butter on one slice of bread. Spread jelly on another slice of bread. put the halves together and enjoy ").save()

class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
